image: databaseline/zoose-pytorch-gitpod:3.3.0

ports:
  - name: JupyterLab
    description: JupyterLab port
    port: 8888
    onOpen: open-browser
  - name: TensorBoard
    description: Default port
    port: 6006
    onOpen: open-browser

vscode:
  extensions:
    - ms-python.python
    - ms-python.black-formatter
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - ms-toolsai.vscode-jupyter-powertoys
    - ms-pyright.pyright
    - ms-vscode.references-view
